---
- name: generator ISUCON_SUBDOMAIN_ADDRESS
  become: true
  copy:
    content: |
      #!/usr/bin/env bash
      set -eux
      if (test -f /opt/aws-env-isucon-subdomain-address.sh.lock); then
        exit
      fi
      touch /opt/aws-env-isucon-subdomain-address.sh.lock
      instance_ip=$(curl -m 10 -s curl http://169.254.169.254/latest/meta-data/public-ipv4)
      if [ -n $instance_ip ]; then
        sed -Ei 's/^ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS=.+$/ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="'${instance_ip}'"/' /home/isucon/env.sh
      fi
      chmod 0755 /home/isucon/env.sh
      chown isucon:isucon /home/isucon/env.sh
    dest: /opt/aws-env-isucon-subdomain-address.sh
    owner: root
    group: root
    mode: 0755

- name: generator ISUCON_SUBDOMAIN_ADDRESS service
  become: true
  copy:
    content: |
      [Unit]
      Description=run aws-env-isucon-subdomain-address once
      Wants=time-sync.target
      Before=time-sync.target
      After=network.target
      
      [Service]
      Restart=no
      Type=simple
      RemainAfterExit=yes
      ExecStart=/opt/aws-env-isucon-subdomain-address.sh
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/aws-env-isucon-subdomain-address.service
    mode: 0644

- name: Enable test service
  become: true
  service:
    name: aws-env-isucon-subdomain-address
    enabled: true
