---
- name: Send webapp tarball
  become: true
  ansible.builtin.copy:
    src: webapp.tar.gz
    dest: /home/isucon/webapp.tar.gz
- name: Extract webapp.tar.gz into /home/isucon
  become: true
  become_user: isucon
  ansible.builtin.unarchive:
    src: /home/isucon/webapp.tar.gz
    dest: /home/isucon/webapp
- name: Remove webapp.tar.gz
  become: true
  ansible.builtin.file:
    path: /home/isucon/webapp.tar.gz
    state: absent
- name: Tasks for isupipe-go
  include_tasks: go.yaml
- name: Put systemd service
  become: true
  ansible.builtin.copy:
    src: isupipe-go.service
    dest: /etc/systemd/system/
- name: Put systemd service env file
  become: true
  ansible.builtin.template:
    src: env.sh
    dest: /home/isucon/
- name: Start webapp
  become: true
  service:
    name: isupipe-go
    enabled: true
    state: restarted
