---
- name: "roles/nginx/tasks: Install package"
  apt:
    name:
    - nginx
    update_cache: yes

- name: "roles/nginx/tasks: Mkdir for config files"
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: 0755

- name: "roles/nginx/tasks: Deploy nginx configs"
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
  - etc/nginx/conf.d/nginx.conf

- name: "roles/nginx/tasks: Delete default config"
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "roles/nginx/tasks: Start nginx"
  systemd:
    daemon_reload: "yes"
    name: "nginx"
    state: "reloaded"
    enabled: "yes"
